let data1 = new Date();
console.log(data1.getHours());
console.log(data1.getHours());
console.log(data1.getFullYear());
console.log(data1.getTime());
console.log(data1.getSeconds());
console.log(data1.getSeconds());
let data2 = new Date(Date.parse("March 10, 2018"));
console.log(data2);
console.log(Date.parse("March 10, 2018"));
console.log(data1.getDate()+"/"+(data1.getMonth()+1)+"/"+data1.getFullYear());
let dias = ['Domingo', 'Segunda', 'Terça', 'Quarta', 'Quinta', 'Sexta', 'Sábado'];
let meses = ['janeiro', 'fevereiro', 'março', 'abril', 'maio', 'junho', 'julho', 'agosto', 'setembro', 'outubro', 'novembro', 'dezembro'];
console.log(dias);
console.log(meses);
console.log(dias[data1.getDay()]);
console.log(data1.getDate()+"/"+meses[data1.getMonth()]+"/"+data1.getFullYear());
data1.setDate(data1.getDate() + 60);
console.log(data1);
data1.setHours(data1.getHours() + 20);
console.log(data1);
